[package]
name = "p2p-sample"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["derive", "env"] }
log = { workspace = true }
rustls = { workspace = true, features = ["ring", "std"] }
serde = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "std"] }
anyhow = { workspace = true }
custom-utils = { path = "../../packages/utils" }
p2p = { workspace = true }
reedline-repl-rs = { workspace = true, features = ["async", "derive"]}